steps:
  # Step 1: Build Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t ${_IMAGE_PATH}/backend:${SHORT_SHA} .

  # Step 2: Push Backend Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_PATH}/backend:${SHORT_SHA}'

  # Step 3: Build Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t ${_IMAGE_PATH}/frontend:${SHORT_SHA} .

  # Step 4: Push Frontend Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_PATH}/frontend:${SHORT_SHA}'

  # Step 5: Deploy Backend Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy backend-service \
        --image ${_IMAGE_PATH}/backend:${SHORT_SHA} \
        --region asia-south1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME}

  # Step 6: Deploy Frontend Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy frontend-service \
        --image ${_IMAGE_PATH}/frontend:${SHORT_SHA} \
        --region asia-south1 \
        --platform managed \
        --allow-unauthenticated

images:
  # Specify the Docker images to be produced and pushed
  - '${_IMAGE_PATH}/backend:${SHORT_SHA}'
  - '${_IMAGE_PATH}/frontend:${SHORT_SHA}'

logsBucket: gs://cloudbuild-logs

substitutions:
  _IMAGE_PATH: asia-south1-docker.pkg.dev/vs-code-proj/Web_App_Node_JS
  _DB_HOST: 34.71.152.233
  _DB_USER: root
  _DB_PASSWORD: Sathi@1993
  _DB_NAME: GenAI
  SHORT_SHA: ${COMMIT_SHA:0:7}
